### ISSUE TITLE
PUBLIC_PATH support upstream

### ISSUE THREAD

**Issue by felipemontoya** [eduNEXT/tutor-contrib-mfe-extensions#3]
https://github.com/openedx/frontend-platform/pull/568 was merged at the end of september. This was a replacement of https://github.com/openedx/frontend-build/pull/398.

Does this fix the annotation in the readme?

> We use webpack's [output.publicPath](https://webpack.js.org/configuration/output/#outputpublicpath) to accomplish this. Due to current limitations in the building scripts we need to use a custom version of [frontend-build](https://github.com/eduNEXT/frontend-build/branches/all?query=cdn). Until https://github.com/openedx/frontend-build/pull/398 is merged.

**Comment by MoisesGSalas** [comment]
The releases for >=v17 are using all the upstream version by default.
